# Generated by Django 5.0.1 on 2024-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=24)),
                ('location', models.CharField(max_length=64)),
                ('share_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Props',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.IntegerField(unique=True)),
                ('field', models.CharField(max_length=64)),
                ('scheme', models.IntegerField()),
                ('type_id', models.IntegerField()),
            ],
        ),
    ]
