# Generated by Django 5.0.1 on 2024-05-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_printer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='props',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='props',
            name='type_id',
        ),
    ]
