# Generated by Django 5.0.1 on 2024-05-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_props_scheme_remove_props_type_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insightentity',
            old_name='scheme',
            new_name='schema',
        ),
    ]
