# Generated by Django 5.0.1 on 2024-05-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_scheme_insightentity_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('ZPL_Text', models.CharField(max_length=64)),
                ('Label_App', models.CharField(max_length=64)),
                ('Label_ID', models.CharField(max_length=64)),
                ('Label_Type', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'LabelTemplate',
                'verbose_name_plural': 'LabelTemplates',
            },
        ),
    ]
