# Generated by Django 5.0.1 on 2024-09-26 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_labeltemplates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insightentity',
            name='props',
        ),
        migrations.AddField(
            model_name='props',
            name='referenced',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props', to='api.insightentity'),
        ),
    ]
