# Generated by Django 5.0.1 on 2024-10-11 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_insightentity_props_props_referenced'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropsTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Типы атрибутов',
                'verbose_name_plural': 'Типы атрибутов',
            },
        ),
        migrations.AddField(
            model_name='props',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='api.propstypes'),
        ),
    ]
