# Generated by Django 5.0.1 on 2024-10-12 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_propstypes_props_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='props',
            name='value_referenced',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='api.insightentity'),
        ),
    ]
