# Generated by Django 5.0.1 on 2024-04-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idam', models.CharField(max_length=4, unique=True)),
                ('insight_id', models.IntegerField(unique=True)),
                ('insight', models.CharField(max_length=4, unique=True)),
                ('jira', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
        ),
    ]
